server:
  port: 8081
spring:
  application:
    name: account-server
    # Nacos 注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 106.12.33.119:8848
    # seata 服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
    # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata-account?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
logging:
  level:
    io:
      seata: debug
mybatis:
  type-aliases-package: com.spring.accountservice.entity
  mapper-locations: classpath:mapper/*.xml
